env:
  GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx4g -Dorg.gradle.daemon=false -Dkotlin.incremental=false"
  RUNNING_ON_CI: "true"
  LC_ALL: C.UTF-8
  LANG: C.UTF-8
  GITHUB_PACKAGES_USERNAME: ${{ github.actor }}
  GITHUB_PACKAGES_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
  PUBLISH_APPS: "false"

on: [push, workflow_dispatch]

jobs:
  publish:
    name: Publish packages
    if: ${{ startsWith(github.ref, 'refs/tags/v-') }}
    runs-on: ubuntu-latest
    env:
      PUBLISHING: "true"
    steps:
      - name: Get tag
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/tags/}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Install JDK
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: adopt
      - name: Configure Gradle
        run: ./gradlew clean
      - name: Build project
        run: ./gradlew assemble --stacktrace
      - name: Upload the apk
        uses: actions/upload-artifact@master
        with:
          name: covpass-${{ steps.vars.outputs.tag }}
          path: |
            app-covpass-prod/build/outputs/apk/debug/covpassprod-*-debug.apk
            app-covpass-check-prod/build/outputs/apk/debug/covpasscheckprod-*-debug.apk
      - name: Publish package
        run: ./gradlew publish
        env:
          PUBLICATION_URL: https://maven.pkg.github.com/Digitaler-Impfnachweis/covpass-android
          PUBLICATION_USERNAME: ${{ github.actor }}
          PUBLICATION_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
